### ISSUE TITLE
StackBlitz

### ISSUE THREAD

**Issue by Alexikon** [rstropek-teaching/turmrechnen-quiz-4bhif-Alexikon#1]
Code: https://stackblitz.com/edit/alexikon-angular-turmrechnen?embed=1&file=app/app.component.html
(Embedded, weil eig. nur Entwickler den Code bearbeiten sollte)

App: https://alexikon-angular-turmrechnen.stackblitz.io

soll ich es auch noch selber im VSCode schreiben und auf GitHub laden oder passt es so?

**Comment by rstropek** [comment]
Hi @Alexikon 

Well done, your extra point is secured.

Greetings,
Rainer Stropek.
